Version:1.0 StartHTML:0000000128 EndHTML:0000006302 StartFragment:0000000128 EndFragment:0000006302 SourceURL:about:blank
DATA:
  data_root: ../../data_smk_density
  train_list: [../../data_smk_density/datalist/background_list.txt,
               ../../data_smk_density/datalist/smk_fg_synth.txt]
  val_list: None
  classes: 2

TRAIN:
  arch: tanet
  layers: 18
  dataset: smoke
  backbone: mobile # resnet18
  sync_bn: False  # adopt sync_bn or not
  train_size: 256
  scale_min: 0.6  # >=154
  scale_max: 1.2  # <=307
  rotate_min: -90  # minimum random rotate
  rotate_max: 90  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  aux_weight: 0.4
  train_gpu: [0]
  workers: 0  # data loader workers 4
  batch_size: 8
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 
  print_freq: 50
  save_freq: 1
  weight:  # pretrained weight
  resume:  #
  evaluate: True
  eval_interval: 1
  seed: #seed

 # TEST:
  test_list: [../../data_smk_density/datalist/SD03_all_img.txt,
  ../../data_smk_density/datalist/SD03_all_alpha.txt]  #
#  test_list: [ ../../data_smk_density/datalist/test14_sizes.txt]
  img_size: 256
  scales: [1.0]
  has_prediction: False  # has prediction already or not
  test_gpu: [0]
  model_path: ../tools/run/smoke/mobilenet1/experiment_0/train_epoch_131.pth
